apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search-quickstart
spec:
  version: 7.15.0
  count: 1
  elasticsearchRef:
    name: quickstart
  podTemplate:
    spec:
      tolerations:
      - key: "stack"
        operator: "Equal"
        value: "eck"
        effect: "NoSchedule"