apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastisearch-main
spec:
  version: 7.15.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        tolerations:
        - key: "stack"
          operator: "Equal"
          value: "eck"
          effect: "NoSchedule"


# curl -u "elastic:eX3NrYYawifMquKnOs8fQDAo" -k "https://quickstart-es-http:9200"